create table food (
  id bigint generated by default as identity primary key,
  name text not null,
  calories integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table exercise (
  id bigint generated by default as identity primary key,
  name text not null,
  calories_burned integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table metrics (
  id bigint generated by default as identity primary key,
  weight double precision not null,
  height double precision not null,
  bmi double precision not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table food enable row level security;
create policy "Allow all access to food" on food for all using (true) with check (true);

alter table exercise enable row level security;
create policy "Allow all access to exercise" on exercise for all using (true) with check (true);

create table withings_auth (
  id bigint generated by default as identity primary key,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamp with time zone not null,
  userid text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table withings_auth enable row level security;
create policy "Allow all access to withings_auth" on withings_auth for all using (true) with check (true);

-- Add source/external_id to existing tables
alter table food add column source text default 'manual';
alter table exercise add column source text default 'manual';
alter table exercise add column external_id text;
alter table metrics add column source text default 'manual';
alter table metrics add column external_id text;
