-- User profiles for settings
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  height double precision,
  goal_weight double precision,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table profiles enable row level security;
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);

-- Existing tables with user_id
create table food (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  name text not null,
  calories integer not null,
  source text default 'manual',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table exercise (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  name text not null,
  calories_burned integer not null,
  source text default 'manual',
  external_id text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table metrics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  weight double precision not null,
  height double precision not null,
  bmi double precision not null,
  source text default 'manual',
  external_id text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table withings_auth (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  access_token text not null,
  refresh_token text not null,
  expires_at timestamp with time zone not null,
  userid text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table food enable row level security;
create policy "Users can manage own food" on food for all using (auth.uid() = user_id);

alter table exercise enable row level security;
create policy "Users can manage own exercise" on exercise for all using (auth.uid() = user_id);

alter table metrics enable row level security;
create policy "Users can manage own metrics" on metrics for all using (auth.uid() = user_id);

alter table withings_auth enable row level security;
create policy "Users can manage own withings_auth" on withings_auth for all using (auth.uid() = user_id);

-- Disable all new sign-ups via database trigger
create or replace function block_signup()
returns trigger
language plpgsql
security definer
as $$
begin
  raise exception 'New sign-ups are currently disabled.';
end;
$$;

create trigger block_new_users
before insert on auth.users
for each row execute function block_signup();


