create table food (
  id bigint generated by default as identity primary key,
  name text not null,
  calories integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table exercise (
  id bigint generated by default as identity primary key,
  name text not null,
  calories_burned integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table metrics (
  id bigint generated by default as identity primary key,
  weight double precision not null,
  height double precision not null,
  bmi double precision not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table food enable row level security;
create policy "Allow all access to food" on food for all using (true) with check (true);

alter table exercise enable row level security;
create policy "Allow all access to exercise" on exercise for all using (true) with check (true);

alter table metrics enable row level security;
create policy "Allow all access to metrics" on metrics for all using (true) with check (true);
