-- Create heart_rate table
create table if not exists heart_rate (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  bpm integer not null,
  source text default 'manual',
  external_id text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table heart_rate enable row level security;

-- RLS Policies
create policy "Users can manage own heart_rate" on heart_rate for all using (auth.uid() = user_id);
