-- Create steps table
create table if not exists steps (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  count integer not null,
  source text default 'manual',
  external_id text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table steps enable row level security;

-- RLS Policies (Idempotent)
drop policy if exists "Users can manage own steps" on steps;
create policy "Users can manage own steps" on steps for all using (auth.uid() = user_id);
